### ISSUE TITLE
Semana 1 

### ISSUE THREAD

**Issue by AraceliGS** [AraceliGS/cardify#1]
Metas a realizar durante estos días en colaboración con @LeslyN:

- [x] Inicializar proyecto con npm init y git init.

- [x] Crear y escribir la primera versión del archivo README.md, la cual incluye una descripción general de la librería. 

- [x] Planificar la maquetación del sitio web.

- [x] Hacer la la maquetación del sitio web.

- [x] Crear issues y milestones que sirvan como hoja de ruta.

- [x] Definir como se logrará hacer el plugin del sitio web.

- [x] Terminar el plugin.

- [x] Investigar sobre el archivo gitignore, ECMAScript 6, plugins y otras herramientas relacionadas con la funcionalidad del sitio web.

- [x] Agregar al proyecto el archivo gitignore.

- [x] Realizar el package.json.

**Comment by LeslyN** [comment]
Empezaremos los cambios con la estructura de archivos que vamos a agregar.
