### ISSUE TITLE
Semana 2

### ISSUE THREAD

**Issue by AraceliGS** [AraceliGS/cardify#3]
Metas por alcanzar:
- [x] Terminar la funcionalidad del plugin, empleando función autoejecutable.
- [x]  Añadir los snippets al archivo README.md.
- [x] Agregar prototipado al archivo README.md.

**Comment by LeslyN** [comment]
Se agregó archivo package.json

**Comment by LeslyN** [comment]
Solo nos falta dar estilos en las imágenes con los figcaptions
